/* Definitions for Discord class names. */

import { DsString } from "../lib/discordStyles";

export type DiscordStyles = {
    app0: DsString;
    app1: DsString;
    layers0: DsString;
    layers1: DsString;
    appMount: DsString;
    bg: DsString;
    typeWindows: DsString;
    withFrame: DsString;
    titleBar: DsString;
    horizontalReverse: DsString;
    flex: DsString;
    directionRowReverse: DsString;
    justifyStart: DsString;
    alignStretch: DsString;
    wordmarkWindows: DsString;
    wordmark: DsString;
    winButtonClose: DsString;
    winButtonMinMax: DsString;
    winButton: DsString;
    flexCenter: DsString;
    justifyCenter: DsString;
    alignCenter: DsString;
    layer: DsString;
    standardSidebarView: DsString;
    sidebarRegion: DsString;
    sidebarRegionScroller: DsString;
    thin: DsString;
    scrollerBase: DsString;
    fade: DsString;
    sidebar: DsString;
    side: DsString;
    contentRegion: DsString;
    contentRegionScroller: DsString;
    contentRegionShownSidebar: DsString;
    auto: DsString;
    header: DsString;
    eyebrow: DsString;
    item: DsString;
    themed: DsString;
    selected: DsString;
    separator: DsString;
    socialLinks: DsString;
    anchor: DsString;
    anchorUnderlineOnHover: DsString;
    link: DsString;
    textXsNormal: DsString;
    line: DsString;
    info: DsString;
    sectionTitle: DsString;
    h1: DsString;
    title: DsString;
    defaultColor: DsString;
    defaultMarginh1: DsString;
    contentColumn: DsString;
    contentColumnDefault: DsString;
    container: DsString;
    marginTop8: DsString;
    marginBottom20: DsString;
    textMdNormal: DsString;
    children: DsString;
    divider: DsString;
    marginTop20: DsString;
    note: DsString;
    colorStandard: DsString;
    size14: DsString;
    description: DsString;
    formText: DsString;
    modeDefault: DsString;
    labelRow: DsString;
    dividerDefault: DsString;
    h5: DsString;
    defaultMarginh5: DsString;
    labelTitle: DsString;
    marginBottom8: DsString;
    control: DsString;
    controlContainer: DsString;
    defaultColors: DsString;
    checked: DsString;
    input: DsString;
    slider: DsString;
    betaTagContainer: DsString;
    dependentSetting: DsString;
    betaTagIcon: DsString;
    testBadge: DsString;
    base: DsString;
    badgeEyebrow: DsString;
    baseShapeRound: DsString;
    radioItem: DsString;
    horizontal: DsString;
    radioFlex: DsString;
    directionRow: DsString;
    itemFilled: DsString;
    radioBar: DsString;
    radioInfo: DsString;
    textMdMedium: DsString;
    radioPositionLeft: DsString;
};

const styles: DiscordStyles = {
    app0: undefined,
    app1: undefined,
    layers0: undefined,
    layers1: undefined,
    appMount: undefined,
    bg: undefined,
    typeWindows: undefined,
    withFrame: undefined,
    titleBar: undefined,
    horizontalReverse: undefined,
    flex: undefined,
    directionRowReverse: undefined,
    justifyStart: undefined,
    alignStretch: undefined,
    wordmarkWindows: undefined,
    wordmark: undefined,
    winButtonClose: undefined,
    winButtonMinMax: undefined,
    winButton: undefined,
    flexCenter: undefined,
    justifyCenter: undefined,
    alignCenter: undefined,
    layer: undefined,
    standardSidebarView: undefined,
    sidebarRegion: undefined,
    sidebarRegionScroller: undefined,
    thin: undefined,
    scrollerBase: undefined,
    fade: undefined,
    sidebar: undefined,
    side: undefined,
    contentRegion: undefined,
    contentRegionScroller: undefined,
    contentRegionShownSidebar: undefined,
    auto: undefined,
    header: undefined,
    eyebrow: undefined,
    item: undefined,
    themed: undefined,
    selected: undefined,
    separator: undefined,
    socialLinks: undefined,
    anchor: undefined,
    anchorUnderlineOnHover: undefined,
    link: undefined,
    textXsNormal: undefined,
    line: undefined,
    info: undefined,
    sectionTitle: undefined,
    h1: undefined,
    title: undefined,
    defaultColor: undefined,
    defaultMarginh1: undefined,
    contentColumn: undefined,
    contentColumnDefault: undefined,
    container: undefined,
    marginTop8: undefined,
    marginBottom20: undefined,
    textMdNormal: undefined,
    children: undefined,
    divider: undefined,
    marginTop20: undefined,
    note: undefined,
    colorStandard: undefined,
    size14: undefined,
    description: undefined,
    formText: undefined,
    modeDefault: undefined,
    labelRow: undefined,
    dividerDefault: undefined,
    h5: undefined,
    defaultMarginh5: undefined,
    labelTitle: undefined,
    marginBottom8: undefined,
    control: undefined,
    controlContainer: undefined,
    defaultColors: undefined,
    checked: undefined,
    input: undefined,
    slider: undefined,
    betaTagContainer: undefined,
    dependentSetting: undefined,
    betaTagIcon: undefined,
    testBadge: undefined,
    base: undefined,
    badgeEyebrow: undefined,
    baseShapeRound: undefined,
    radioItem: undefined,
    horizontal: undefined,
    radioFlex: undefined,
    directionRow: undefined,
    itemFilled: undefined,
    radioBar: undefined,
    radioInfo: undefined,
    textMdMedium: undefined,
    radioPositionLeft: undefined
};
export default styles;
